services:
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory
    ports:
      - "1002:8002"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order
    ports:
      - "1001:8001"
    environment:
      INVENTORY_URL: http://inventory-service:8002
    depends_on:
      - inventory-service
